// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFelQtntQg2O7T9humJXbepnqu-jCpprY',
    appId: '1:560333483278:web:your_web_app_id',
    messagingSenderId: '560333483278',
    projectId: 'quitxtmobile',
    authDomain: 'quitxtmobile.firebaseapp.com',
    databaseURL: 'https://quitxtmobile-default-rtdb.firebaseio.com',
    storageBucket: 'quitxtmobile.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFelQtntQg2O7T9humJXbepnqu-jCpprY',
    appId: '1:560333483278:android:477162cb0e780131b8fb5f',
    messagingSenderId: '560333483278',
    projectId: 'quitxtmobile',
    databaseURL: 'https://quitxtmobile-default-rtdb.firebaseio.com',
    storageBucket: 'quitxtmobile.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3U2IV08Nh_pfs3VVpyn8GE1tG7qLwJrA',
    appId: '1:560333483278:ios:05dfdea509de9518b8fb5f',
    messagingSenderId: '560333483278',
    projectId: 'quitxtmobile',
    databaseURL: 'https://quitxtmobile-default-rtdb.firebaseio.com',
    storageBucket: 'quitxtmobile.firebasestorage.app',
    iosBundleId: 'com.utsascns.quitTxTapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3U2IV08Nh_pfs3VVpyn8GE1tG7qLwJrA',
    appId: '1:560333483278:ios:05dfdea509de9518b8fb5f',
    messagingSenderId: '560333483278',
    projectId: 'quitxtmobile',
    databaseURL: 'https://quitxtmobile-default-rtdb.firebaseio.com',
    storageBucket: 'quitxtmobile.firebasestorage.app',
    iosBundleId: 'com.utsascns.quitTxTapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDFelQtntQg2O7T9humJXbepnqu-jCpprY',
    appId: '1:560333483278:web:your_web_app_id',
    messagingSenderId: '560333483278',
    projectId: 'quitxtmobile',
    authDomain: 'quitxtmobile.firebaseapp.com',
    databaseURL: 'https://quitxtmobile-default-rtdb.firebaseio.com',
    storageBucket: 'quitxtmobile.firebasestorage.app',
  );
}