// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // DEMO/THESIS VERSION - Using placeholder credentials
  // These are NOT connected to any production Firebase project
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'DEMO-API-KEY-WEB',
    appId: '1:000000000000:web:demo_app_id',
    messagingSenderId: '000000000000',
    projectId: 'quittxt-demo',
    authDomain: 'quittxt-demo.firebaseapp.com',
    databaseURL: 'https://quittxt-demo-default-rtdb.firebaseio.com',
    storageBucket: 'quittxt-demo.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'DEMO-API-KEY-ANDROID',
    appId: '1:000000000000:android:demo_android_id',
    messagingSenderId: '000000000000',
    projectId: 'quittxt-demo',
    databaseURL: 'https://quittxt-demo-default-rtdb.firebaseio.com',
    storageBucket: 'quittxt-demo.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'DEMO-API-KEY-IOS',
    appId: '1:000000000000:ios:demo_ios_id',
    messagingSenderId: '000000000000',
    projectId: 'quittxt-demo',
    databaseURL: 'https://quittxt-demo-default-rtdb.firebaseio.com',
    storageBucket: 'quittxt-demo.firebasestorage.app',
    iosBundleId: 'com.demo.quittxt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'DEMO-API-KEY-MACOS',
    appId: '1:000000000000:ios:demo_macos_id',
    messagingSenderId: '000000000000',
    projectId: 'quittxt-demo',
    databaseURL: 'https://quittxt-demo-default-rtdb.firebaseio.com',
    storageBucket: 'quittxt-demo.firebasestorage.app',
    iosBundleId: 'com.demo.quittxt',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'DEMO-API-KEY-WINDOWS',
    appId: '1:000000000000:web:demo_windows_id',
    messagingSenderId: '000000000000',
    projectId: 'quittxt-demo',
    authDomain: 'quittxt-demo.firebaseapp.com',
    databaseURL: 'https://quittxt-demo-default-rtdb.firebaseio.com',
    storageBucket: 'quittxt-demo.firebasestorage.app',
  );
}